Remove gcp code from workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -25,103 +25,103 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
-      - id: 'auth'
-        uses: 'google-github-actions/auth@v2'
-        with:
-          service_account: ${{ vars.SVCACCOUNT }}
-          workload_identity_provider: ${{ vars.WORKLOAD }}
-
-      # nicked from https://github.com/Azure-Samples/terraform-github-actions/blob/main/.github/workflows/tf-plan-apply.yml
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v3
-        with:
-          terraform_wrapper: false
-
-      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
-      - name: Terraform Init
-        run: terraform init -backend-config="prefix=${{ inputs.environment }}"
-
-      # Checks that all Terraform configuration files adhere to a canonical format
-      # Will fail the build if not
-      - name: Terraform Format
-        run: terraform fmt -check
-
-      # Generates an execution plan for Terraform
-      # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
-      - name: Terraform Plan
-        id: tf-plan
-        run: |
-          export exitcode=0
-          terraform plan -var-file="conf/${{ inputs.environment }}.tfvars" -detailed-exitcode -no-color -out tfplan-${{ inputs.environment }} || export exitcode=$?
-
-          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
-
-          if [ $exitcode -eq 1 ]; then
-            echo Terraform Plan Failed!
-            exit 1
-          else
-            exit 0
-          fi
-
-      # Save plan to artifacts
-      - name: Publish Terraform Plan
-        uses: actions/upload-artifact@v4
-        with:
-          name: tfplan-${{ inputs.environment }}
-          path: tfplan-${{ inputs.environment }}
-
-      # Create string output of Terraform Plan
-      - name: Create String Output
-        id: tf-plan-string
-        run: |
-          TERRAFORM_PLAN=$(terraform show -no-color tfplan-${{ inputs.environment }})
-
-          delimiter="$(openssl rand -hex 8)"
-          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
-          echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
-          echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
-          echo "" >> $GITHUB_OUTPUT
-          echo '```terraform' >> $GITHUB_OUTPUT
-          echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
-          echo '```' >> $GITHUB_OUTPUT
-          echo "</details>" >> $GITHUB_OUTPUT
-          echo "${delimiter}" >> $GITHUB_OUTPUT
-
-      # Publish Terraform Plan as task summary
-      - name: Publish Terraform Plan to Task Summary
-        env:
-          SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
-        run: |
-          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
-
-      # If this is a PR post the changes
-      - name: Push Terraform Output to PR
-        if: github.ref != 'refs/heads/main'
-        uses: actions/github-script@v7
-        env:
-          SUMMARY: "${{ steps.tf-plan-string.outputs.summary }}"
-        with:
-            github-token: ${{ secrets.GITHUB_TOKEN }}
-            script: |
-              const body = `${process.env.SUMMARY}`;
-              github.rest.issues.createComment({
-                  issue_number: context.issue.number,
-                  owner: context.repo.owner,
-                  repo: context.repo.repo,
-                  body: body
-              })
-
-    terraform-apply:
-      name: 'Terraform Apply'
-      if: github.ref == 'refs/heads/main' && needs.terraform-plan.outputs.tfplanExitCode == 2
-      runs-on: ubuntu-latest
-      environment: ${{ inputs.environment }}
-      needs: [terraform-plan]
-
-      steps:
-      # Checkout the repository to the GitHub Actions runner
-      - name: Checkout
-        uses: actions/checkout@v4
+#      - id: 'auth'
+#        uses: 'google-github-actions/auth@v2'
+#        with:
+#          service_account: ${{ vars.SVCACCOUNT }}
+#          workload_identity_provider: ${{ vars.WORKLOAD }}
+#
+#      # nicked from https://github.com/Azure-Samples/terraform-github-actions/blob/main/.github/workflows/tf-plan-apply.yml
+#      - name: Setup Terraform
+#        uses: hashicorp/setup-terraform@v3
+#        with:
+#          terraform_wrapper: false
+#
+#      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+#      - name: Terraform Init
+#        run: terraform init -backend-config="prefix=${{ inputs.environment }}"
+#
+#      # Checks that all Terraform configuration files adhere to a canonical format
+#      # Will fail the build if not
+#      - name: Terraform Format
+#        run: terraform fmt -check
+#
+#      # Generates an execution plan for Terraform
+#      # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
+#      - name: Terraform Plan
+#        id: tf-plan
+#        run: |
+#          export exitcode=0
+#          terraform plan -var-file="conf/${{ inputs.environment }}.tfvars" -detailed-exitcode -no-color -out tfplan-${{ inputs.environment }} || export exitcode=$?
+#
+#          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+#
+#          if [ $exitcode -eq 1 ]; then
+#            echo Terraform Plan Failed!
+#            exit 1
+#          else
+#            exit 0
+#          fi
+#
+#      # Save plan to artifacts
+#      - name: Publish Terraform Plan
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: tfplan-${{ inputs.environment }}
+#          path: tfplan-${{ inputs.environment }}
+#
+#      # Create string output of Terraform Plan
+#      - name: Create String Output
+#        id: tf-plan-string
+#        run: |
+#          TERRAFORM_PLAN=$(terraform show -no-color tfplan-${{ inputs.environment }})
+#
+#          delimiter="$(openssl rand -hex 8)"
+#          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
+#          echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
+#          echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
+#          echo "" >> $GITHUB_OUTPUT
+#          echo '```terraform' >> $GITHUB_OUTPUT
+#          echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
+#          echo '```' >> $GITHUB_OUTPUT
+#          echo "</details>" >> $GITHUB_OUTPUT
+#          echo "${delimiter}" >> $GITHUB_OUTPUT
+#
+#      # Publish Terraform Plan as task summary
+#      - name: Publish Terraform Plan to Task Summary
+#        env:
+#          SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
+#        run: |
+#          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
+#
+#      # If this is a PR post the changes
+#      - name: Push Terraform Output to PR
+#        if: github.ref != 'refs/heads/main'
+#        uses: actions/github-script@v7
+#        env:
+#          SUMMARY: "${{ steps.tf-plan-string.outputs.summary }}"
+#        with:
+#            github-token: ${{ secrets.GITHUB_TOKEN }}
+#            script: |
+#              const body = `${process.env.SUMMARY}`;
+#              github.rest.issues.createComment({
+#                  issue_number: context.issue.number,
+#                  owner: context.repo.owner,
+#                  repo: context.repo.repo,
+#                  body: body
+#              })
+#
+#    terraform-apply:
+#      name: 'Terraform Apply'
+#      if: github.ref == 'refs/heads/main' && needs.terraform-plan.outputs.tfplanExitCode == 2
+#      runs-on: ubuntu-latest
+#      environment: ${{ inputs.environment }}
+#      needs: [terraform-plan]
+#
+#      steps:
+#      # Checkout the repository to the GitHub Actions runner
+#      - name: Checkout
+#        uses: actions/checkout@v4
 
 #      - id: 'auth'
 #        uses: 'google-github-actions/auth@v2'
